<?xml version="1.0"?>
<robot name="lidar" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="lidar_height" value="0.041" />
  <xacro:property name="lidar_radius" value="0.038" />

  <xacro:macro name="lidar" params="x y z r">
    <link name="lidar_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${r*pi/2}" />
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}" />
        </geometry>
        <material name="Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.125" />
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
      </inertial>
    </link>

    <joint name="lidar_joint" type="fixed">
      <parent link="base_link" />
      <child link="lidar_link" />
      <origin xyz="${x} ${y} ${z+lidar_height/2}" rpy="0 0 0" />
    </joint>

    <gazebo reference="lidar_link">
      <sensor name="lidar" type="ray">
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>5</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1.000000</resolution>
              <min_angle>0.000000</min_angle>
              <max_angle>6.280000</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.120000</min>
            <max>3.5</max>
            <resolution>0.015000</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <remapping>~/out:=scan</remapping>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frame_name>lidar_link</frame_name>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>