<?xml version="1.0"?>
<robot name="caster" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="caster_radius" value="0.035" />
    <xacro:property name="caster_width" value="0.02" />

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <mass value="${m}" />
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0" iyy="${(m/12) * (3*r*r + h*h)}" iyz="0" izz="${(m/2) * (r*r)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

    <xacro:macro name="caster" params="parent prefix ztotal x y z">
        <link name="${prefix}_link">
            <visual>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
                <sphere radius="${caster_radius}" />
              </geometry>
              <material name="Black"/>
            </visual>
      
            <collision>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
                <cylinder radius="${caster_radius}" length="${caster_width}" />
              </geometry>
            </collision>
      
            <xacro:sphere_inertia m="0.5" r="${caster_radius}"/>
          </link>

          <joint name="${prefix}_joint" type="continuous">
            <parent link="${parent}" />
            <child link="${prefix}_link" />
            <origin xyz="${x} ${y} ${-(ztotal-caster_radius)}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
          </joint>
    </xacro:macro>

    <!-- <xacro:beam prefix="c1" parent="base_link" length="0.48" height="0.02" x="0" y="0" z="0" r="1" /> -->
</robot>